//国内音乐
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/AQiao-PWQLL.mp3","阿悄 - 陪我去流浪");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/CaiYiLin-IKnowYouSad.wma","蔡依林 - 我知道你很难过");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/CaiYiLin-SunBL.wma","蔡依林 - 日不落");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/CaiYiLin-LOVELOVELOVE.Wma","蔡依林 - LOVE LOVE LOVE");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/CJY-WuDiDong.wma","蔡健雅 - 无底洞");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ChenBQ-YSHQ.wma","陈百强 - 一生何求");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/Chenbq-LikeYou.wma","陈百强 - 偏偏喜欢你");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ChenCS-TellYou.wma","陈楚生 - 有没有人告诉你");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ChenFP-HowLang.wma","陈妃平 - 永远到底有多远");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ChenHong-ChangANjie.wma","陈红 - 走过长安街");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ChenHL-NoteBook.mp3","陈慧琳 - 记事本");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ChenGP-TaiDuo.wma","陈冠蒲 - 太多");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ChenGP-LetYouGo.wma","陈冠蒲 - 就让你走");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ChenSH-OneNightInBeiJing.wma","陈升 刘佳慧 - 北京一夜");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ChenSH-QingGuan.wma","陈淑桦 - 情关");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ChenSH-Mengxsf.wma","陈淑桦 - 梦醒时分");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ChenSH-Xiaohc.mp3","陈淑桦 - 笑红尘");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ChenYx-LoveMove.wma","陈奕迅 - 爱情转移");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ChenYx-10N.mp3","陈奕迅 - 十年");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ChengLong-LoveNoEnd.wma","成龙 金喜善 - 无尽的爱");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/CuiZG-BuGua.mp3","崔子格 - 卜卦");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/DaoLang-LoveYouMe.wma","刀郎 - 爱是你我");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/DengZQ-NiBWGZ.mp3","邓紫棋 - 你把我灌醉");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/DengZQ-LoveYou.mp3","邓紫棋 - 喜欢你");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/DengZQ-PaoMo.mp3","邓紫棋 - 泡沫");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/DingDang-CaiBuTou.mp3","丁当 - 猜不透");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/FanWQ-ZZYDJD.mp3","范玮琪 - 最重要的决定");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/FIR-1000YEARS.wma","飞儿乐团 - 千年之恋");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/FengFF-dream.mp3","凤飞飞 - 追梦人");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/FengHCQ-HeTYS.mp3","凤凰传奇 - 荷塘月色");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/FengHCQ-LangDYH.mp3","凤凰传奇 - 郎的诱惑");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/GaoAN-LoveSong.mp3","高安,黑鸭子 - 红尘情歌");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/GeGe-fire.mp3","格格 - 火苗");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/Gongweite-xnxdyll.mp3","贡维特 - 想你想到眼泪流");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/GuangL-TongHua.mp3","光良 - 童话");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/GuangLiang-AllYou.wma","光良 - 都是你");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/GuoMM-LoveNS.wma","郭美美 - 爱情女神");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/HaiMW-OldMan.wma","海鸣威 - 老人与海");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/HanHong-Tianll.mp3","韩红 - 天亮了");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/HanHong-TianLu.mp3","韩红 - 天路");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/HanXue-XiangQi.wma","韩雪 - 想起");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/HaoHan-FenSZNGQT.wma","浩瀚 - 分手在那个秋天");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/HeLu-LetHerDown.Wma","何璐 - 让她降落");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/HuYL-XSYD.wma","胡杨林 - 香水有毒");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/HuangXH-MeiNMJD.mp3","黄小琥 - 没那么简单");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/HunZun-JuanZL.mp3","霍尊 - 卷珠帘");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/JiangMQ-NotByMe.wma","江美琪 - 亲爱的你怎么不在我身边");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/Jxuer-WhyCareMe.mp3","蒋雪儿 - 谁在意我留下的泪");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/KanKan-DiDa.mp3","侃侃 - 滴答");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LaoLang-TZDN.wma","老狼 - 同桌的你");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiCH-Rainday.Wma","李彩桦 - 我爱雨天");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiHuiZ-XG.mp3","李慧珍 - 习惯");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiWen-365day.mp3","李玟 - 想你的365天");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiWen-MoonLover.mp3","李玟 - 月光爱人");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiSJ-CXJD.wma","李圣杰 - 痴心绝对");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiSJ-HandKAI.wma","李圣杰 - 手放开");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiXJ-PYDJ.mp3","李晓杰 - 朋友的酒");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiYuC-LiHX.wma","李宇春 - 梨花香");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiYuG-XGFZJ.mp3","李玉刚 - 新贵妃醉酒");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiYuG-JuHT.mp3","李玉刚 - 菊花台");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiYuG-SiKBLJS.mp3","李玉刚 - 斯卡博罗集市");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiangJR-NotYou.mp3","梁静茹 - 可惜不是你");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LinZX-BuZW.wma","林宸希 - 不再问");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LinXinRu-LuoHua.mp3","林心如 - 落花");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LinXinRu-QingTingWo.mp3","林心如 - 倾听我");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LinYJ-YouMyEye.mp3","林宥嘉 - 你是我的眼");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiuDeH-LoveNotEnough.wma","刘德华&陈慧琳 - 我不够爱你");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiuRY-HenAhAIn.wma","刘若英 - 很爱很爱你");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiuSS-DNDJJ.mp3","刘诗诗 - 等你的季节");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LinZX-MeiLKG.mp3","林志炫 - 没离开过");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LinZX-YanHYL.mp3","林志炫 - 烟花易冷");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiuKeYi-BanHS.mp3","刘珂矣 - 半壶纱");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiuKeYi-FengZW.mp3","刘珂矣 - 风筝误");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiuKeYi-FURY.mp3","刘珂矣 - 芙蓉雨");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiuKeYi-NuanShan.mp3","刘珂矣 - 暖山");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiuKeYi-PiaoMZ.mp3","刘珂矣 - 缥缃醉");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiuKeYi-PoCX.mp3","刘珂矣 - 泼茶香");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiuKeYi-WangCG.mp3","刘珂矣 - 忘尘谷");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LiuZhe-Cuo3.mp3","六哲 - 错错错");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LuoDaY-Love1990.wma","罗大佑 - 恋曲1990");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/LuGT-YiSSA.mp3","卢冠廷 - 一生所爱");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/MaTY-GSDWR.wma","马天宇 - 该死的温柔");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/MaYu-XBZHJDN.wma","马郁 - 下辈子如果我还记得你");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/MaYu-YTSQYD.wma","马郁 - 一天死去一点");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/MuRXX-AiQingMM.wma","慕容晓晓 - 爱情买卖");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/MengTW-Winter.mp3","孟庭苇 - 冬季到台北来看雨");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/MengTW-Cloud.mp3","孟庭苇 - 风中有朵雨做的云");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/MengTW-Tear.mp3","孟庭苇 - 谁的眼泪在飞");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/MoWenW-GDZL.wma","莫文蔚 张洪量 - 广岛之恋");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/MoWenW-SXDGS.wma","莫文蔚 - 盛夏的果实");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/PanYueYun-WSBSNZTDR.wma","潘越云 - 我是不是你最疼爱的人");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/QiuYC-11year.mp3","邱永传 - 十一年");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/SaBL-AnX.wma","沙宝亮 - 暗香");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/SaDingDing-WanWuSH.wma","萨顶顶 - 万物生");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ShiTou-YuHuaSHi.mp3","石头 李玉刚 - 雨花石");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ShiTou-jqdst.mp3","石头 - 坚强的石头");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/SiQGL-FanCuo.wma","斯琴高丽 - 犯错");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/SuRui-QianSHou.mp3","苏芮 - 牵手");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/SuYK-ANGRHN.wma","苏永康 - 爱一个人好难");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/SuYK-NRBGRNRLL.wma","苏永康 - 男人不该让女人流泪");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/TangChao-MeiL.mp3","汤潮 - 美了美了");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/TaiJY-TaiWQ.wma","陶晶莹 - 太委屈");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/JiangSL-BFSDLAI.mp3","汪苏泷 - 不分手的恋爱");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/WangQiang-YourLoveWho.mp3","王强 - 你把爱情给了谁");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/WangRong-BBMM.wma","王蓉 - 爸爸妈妈");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/WangXP-WHoAmI.wma","王馨平 - 别问我是谁");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/WangYa-LoveCuoJue.mp3","王娅 - 爱情错觉");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/WangZL-Time.mp3","王铮亮 - 时间都去哪儿了");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/WuLanTY-TaoMaGan.wma","乌兰托娅 - 套马杆");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/WangFei-ForLove.mp3","王菲 陈奕迅 - 因为爱情");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/WangFei-ChuanQi.wma","王菲 - 传奇");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/WangFei-XWS.wma","王菲 - 笑忘书");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/WangJie-Sad1999.wma","王杰 - 伤心1999");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/WangJie-Love.wma","王杰 - 为了爱梦一生");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/WangLin-ShangBQ.mp3","王麟 - 伤不起");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/WuDaMu-MZDEJ.wma","乌达木 - 梦中的额吉");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XiYou-EGSBS.mp3","西游降魔 - 儿歌三百首");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XiYa-XinZui.mp3","希亚 - 心醉");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XiaoX-JJDJQ.mp3","萧萧 - 倔强的坚强");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XiaoYX-LoveZDG.wma","萧亚轩 - 爱的主打歌");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XiaoSY-ALLgOOD.mp3","小沈阳 - 都要好好的");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XieJun-XinZaiT.wma","谢军 - 心在跳情在烧");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XieYuX-BuBuG.wma","谢雨欣 - 步步高");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XieYuX-3day.wma","谢雨欣 - 第三天");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XieYuX-TXZ.wma","谢雨欣 - 天仙子");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XinYueT-JiaRu.mp3","信乐团 - 假如");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XinYueT-LiGe.mp3","信乐团 - 离歌");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XinYueT-HKTK.mp3","信乐团 - 海阔天空");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XuHY-FenFei.mp3","徐怀钰 - 分飞");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XuQYa-CaiYunZN.mp3","徐千雅 - 彩云之南");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XuYT-1Fenz.wma","徐誉滕 - 等一分钟");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XuHuiX-7M7D.wma","许慧欣 - 七月七日晴");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XuMeiJ-CityMoon.wma","许美静 - 城里的月光");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XuMeiJ-SunBRian.wma","许美静 - 阳光总在风雨后");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XuRuYun-DuJX.mp3","许茹芸 - 独角戏");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XuRuYun-LeiHai.mp3","许茹芸 - 泪海");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XuRuYun-RiGJC.mp3","许茹芸 - 日光机场");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/XuRuYun-RuGYZD.mp3","许茹芸 - 如果云知道");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/YJLZ-YJNSWDY.wma","央金兰泽 - 遇上你是我的缘");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/YanYiDan-3CunTT.mp3","严艺丹 - 三寸天堂");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/YanYD-DengNDJJ.mp3","严艺丹 - 等你的季节");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/YangKun-WuSuoWei.wma","杨坤 - 无所谓");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/YangPeian-IBelive.mp3","杨培安 - 我相信");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/YangPeian-ASNSYGC.wma","杨培安 - 爱上你是一个错");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/YangQH-XiaoCDS.wma","杨千桦 - 小城大事");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/YangZW-LiangLiang.mp3","杨宗纬 张碧晨 - 凉凉");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/YuTF-GDTGDD.wma","宇桐非 - 感动天感动地");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZBZ-XYXY.wma","张柏芝 - 星语心愿");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZengCN-ZuiXFDR.mp3","曾春年 - 最幸福的人");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZhangGR-QianNYH.mp3","张国荣 - 倩女幽魂");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZhangJ-ZheJSAi.mp3","张杰 - 这,就是爱");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZhangLY-HuaXin.wma","张靓颖 - 画心");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZWJ-YBZYCM.wma","张卫健 - 一辈子一场梦");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZWJ-XXSS.wma","张卫健 - 虚虚实实");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZHangXZ-LoveBL.wma","张信哲 - 爱不留");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZHangXZ-MMM.wma","张信哲 - 某某某");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZXY-DWXQN.wma","张学友 - 当我想起你");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZHangYunJ-PianAi.wma","张芸京 - 偏爱");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZhagngYu-YYNJ.mp3","张宇 - 一言难尽");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZhangHZ-HaoNR.mp3","张镐哲 - 好男人");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZhangHM-TingHai.mp3","张惠妹 - 听海");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZhangSH-PanDL.wma","张韶涵 - 潘朵拉");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZYH-ZLMDS.wma","赵咏华 - 最浪漫的事");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZHengYuan-ZMHXSHW.wma","郑源 - 怎么会狠心伤害我");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZHengYuan-HanJX.mp3","郑源 - 寒江雪");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZX-PiaoY.wma","周迅 - 飘摇");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZhouZP-NYCFHXYDGS.mp3","周治平 - 那一场风花雪月的故事");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZhuangXY-YiHDYH.mp3","庄心妍 - 以后的以后");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/china/ZhuangXY-YiWGSBD.mp3","庄心妍、祁隆 - 一万个舍不得");
//印度音乐
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/in/IN-JMLB.mp3","印度音乐 - 吉米来吧");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/in/IN-NL.mp3","印度音乐 - 奴里");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/in/IN-DBZ.mp3","印度音乐 - 大悲咒");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/in/IN-DJ.mp3","印度音乐 - 酒吧dj音乐");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/in/IN-QZLS.mp3","印度音乐 - 情字路上");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/in/IN-TSZW.mp3","印度音乐 - 天使之吻");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/in/MeghnaMishra-NachdiPhira.mp3","Meghna Mishra - Nachdi Phira");
//韩国音乐
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/korea/Kiss-IMAGIRL.mp3","kiss - 因为是女子");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/korea/rania-drfeelgood.mp3","rania - dr feel good");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/korea/Dana-WorldEnd.Wma","Dana - 到世界尽头");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/korea/WAX-GBHZ.wma","WAX - 改变化装");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/korea/WAX-KWAQ.wma","WAX - 渴望爱情");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/korea/WAX-YUQ.wma","WAX - 余情");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/korea/wondergirls-nobody.wma","wonder girls - nobody");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/korea/FromBeigin.wma","冬季恋歌 - 从开始到现在");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/korea/QIDAO.wma","蓝色生死恋 - 祈祷");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/korea/LXY-AlsoILoveYou.wma","李秀英 - AlsoILoveYou");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/korea/LXY-NEVERAGAIN.Wma","李秀英 - NEVERAGAIN");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/korea/Liuz-ChaCha.mp3","柳真 - Cha Cha");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/korea/MyMemory.mp3","裴勇俊 - My Memory");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/korea/PHJ-Rain.mp3","朴慧京 - Rain");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/korea/SHUX-LALALA.mp3","淑熙 - 啦啦啦");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/korea/YZH-AllGo.mp3","严正花 - 都走吧");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/korea/YZX-ZXYZM.wma","玉珠铉 - 仲夏夜之梦");
//日本音乐
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/japan/ZhongDaoMJ-XueHua.wma","中岛美嘉 - 雪華");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/japan/azu-angel.mp3","azu - angel");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/japan/BQB-fly_high.mp3","滨崎步 - fly high");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/japan/BQB-To_Be.mp3","滨崎步 - To Be");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/japan/CYWL-SCG.mp3","初音未来 - 甩葱歌");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/japan/DZAI-PEACH.mp3","大冢爱 - 桃ノ花ビラ");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/japan/GCXS-FZHZ.mp3","谷村新司 - 风姿花传");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/japan/GCXS-SL.mp3","谷村新司 - 睡莲");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/japan/SNSD-mrtaxi.mp3","少女时代 - mr taxi");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/japan/SNSD-theboys.mp3","少女时代 - the boys");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/japan/YDTG-First_Love.mp3","宇多田光-First_Love");
//泰国音乐
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/th/Focus-WaitForYou.mp3","focus - 等待着你");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/th/lydia-NoCall.mp3","lydia - 为什么不接电话");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/th/sara-JSZDYJM.mp3","sara - 即使知道要见面");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/th/Sara-ZHGNG.mp3","Sara - 总好过难过");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/th/Zaza-KuamPidTidTua.mp3","Zaza-Kuam Pid Tid Tua");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/th/TH-MH.mp3","泰国歌曲 - 慢嗨舞曲");
//欧美音乐
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/usa/XilINDA-MyHeartWillGoOn.mp3","铁达尼号 - my heart will go on");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/usa/avrillavigne-i'mwithyou.mp3","avril lavigne - i'm with you");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/usa/emilia-big_big_world.mp3","emilia - big_big_world");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/usa/Ladygaga-PokerFace.mp3","Lady gaga - Poker Face");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/usa/YesterdayOnceMore.mp3","Yesterday Once More");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/usa/MyNameYiLian.mp3","我的名字叫伊莲");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/usa/groovecoverage-godisagirl.wma","groove coverage - god is a girl ");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/usa/nana-lonely.wma","nana - lonely");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/usa/sarahconnor-justonelastdance.wma","sarah connor - just one last dance");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/usa/BLN-everytime.wma","布兰妮 - everytime");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/usa/Wts-HTY.wma","维塔斯 - 海豚音");
//空灵音乐
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/adaro-EsIstEinSchneeGefallen.mp3","adaro - Es_Ist_Ein_Schnee_Gefallen");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/amydiamond-Heartbeats.mp3","amy diamond - Heartbeats");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/caradillon-Craigie_Hill.mp3","cara dillon - Craigie_Hill");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/djokawari-luv_letter.mp3","dj okawari - luv_letter");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/enya-Only_Time.mp3","enya - Only_Time");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/hayleywestenra-neversaygoodbye.mp3","hayley westenra - never say goodbye");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/KLER-JRAIYTY.mp3","卡洛儿 - 假如爱有天意");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/KLER-FORSEA.wma","卡洛儿 - 写给海洋");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/sarahbrightman-SKBLJS.mp3","萨拉布莱曼-斯卡布罗集市");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/SYW-therose.mp3","手嶌葵 - the rose");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/SWTLANA-ANGEL.mp3","斯维特拉娜 斯维吉科娃 - 天使消逝的地方");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/YLZH-I_Cry.mp3","有里知花 - I_Cry");
//纯音乐
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/SEN-GGDJY.mp3","S E N 神思者 - 故宫的记忆");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/SEN-BQCS.mp3","s.e.n.s - 悲情城市");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/SMY-LH.wma","神秘园 - 莲花");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/DQSANG.mp3","断情殇");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/tatu-30_Minutes.mp3","t.a.t.u - 30_Minutes");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/madden-aelhm.mp3","爱尔兰口哨女皇 - 爱尔兰画眉");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/WY-Rurutia.mp3","乌鸦 片尾曲 - 月光石");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/yiruma-RAIN.wma","yiruma - 雨的印记");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/YANI-HLHZYQ.wma","YANI - 和兰花在一起");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/XDL-FLYSKY.wma","喜多郎 - 飞天");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/GQJ-SJYY.mp3","宫崎骏 龙猫 - 水晶音乐");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/JSR-SKYCITY.mp3","久石让 - 天空之城");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/BDR-ANDXJ.mp3","班得瑞 - 安妮的仙境");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/BDR-MOON.mp3","班得瑞 - 月光");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/BDR-FZLR.wma","班得瑞 - 非洲日落");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/BDR-XJ.wma","班得瑞 - 仙境");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/LCD-CAJJ.mp3","理查德 克莱德曼 - 出埃及记");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/LCD-MZDHL.mp3","理查德 克莱德曼 - 梦中的婚礼");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/LCD-QRSY.mp3","理查德 克莱德曼 - 秋日私语");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/LCD-SBDADLN.mp3","理查德 克莱德曼 - 水边的阿狄丽娜");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/LCD-WHDLX.wma","理查德 克莱德曼 - 午后的旅行");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/LCD-wnsdwx.mp3","理查德 克莱德曼 - 瓦妮莎的微笑");
mkList("https://cdn.jsdelivr.net/gh/kylehao/free263/music/kong/LCD-ALICE.wma","理查德 克莱德曼 - 致爱丽丝");
